### ISSUE TITLE
Consider using Yeoman

### ISSUE THREAD

**Issue by zewa666** [ahmedshuhel/aurelia-cli#1]
Hi Ahmed,

dunno what this project is going to do in the end, but have you considered using Yeoman and providing an official Yeoman Generator instead? I have been working on quite some CLIs and found that the Yeoman way seems overall much nicer, easier to adopt by newcomers and offers a lot of flexibility and a nice API to build upon.

As a reference might take a short look at my [generator-aurelia](https://github.com/zewa666/generator-aurelia) repo, which creates a new Skeleton App for you. The latest release now also includes auto-updates to always get the latest version from the Github repo, as well as a simple subgenerator for creating a VM/View combination.

**Comment by ahmedshuhel** [comment]
@zewa666  `aurelia-cli` aspires to become something similar to `ember-cli` or `ionic-cli` at first and then grow bigger. We can always work together and build something amazing. Let me know if you want to participate. We can talk more about it.

**Comment by zewa666** [comment]
@ahmedshuhel thx for the information. Yesterday we had a discussion about it in the Gitter channel and I see you guys are heading for something big :) I'm totally fine with either approach be it Yeoman or a custom CLI, was just thinking that by going the Yeoman route we would also market the framework to the large YO Community. Nevermind though its good this way as well.

Would like to contribute where possible so maybe you could lay out some details about the CLI itself? Either in gitter or here via issues, your choice.
